### PR TITLE
add kv store example

### PR DESCRIPTION
**Pull request by gauthamzz**
- added kv store example using py abci
- added readme and requirements.txt for the same

### CODE REVIEW

**Comment by melekes** [comment]
`python3_kvstore` can be renamed to `kvstore`, otherwise LGTM

**Comment by davebryson** [comment]
@gauthamzz  Thanks for the contribution!!   I agree with @melekes, could you please change the name to `kvstore` vs `python3_kvstore`.   Also, it seems like their are unneeded dependencies in  `requirements.txt` .  For example why is their a dependency on Django?  Could you please ensure requirements.txt contains only what's needed for the example.

**Comment by gauthamzz** [comment]
On it 🙂

**Comment by gauthamzz** [comment]
in req, i used older version of trie. Idk where is memoryDB in newer version of trie. Documentation seemed to bad. If you think its fine, do merge.

**Pull request merged**
